---
OBJECTIVE: tweedie
RANDOM_SEED: 42
DEVICE: gpu
LOGS:
  LOGS_PREFIX: lgbm_
  LOGS_LEVEL: INFO
LEARNING:
  NUM_BOOST_ROUND: 1000000
  EARLY_STOPPING_ROUNDS: 500
  HYPER_EVALS: 1
  LEARNING_RATE: 0.1
  LEARN_METRICS_STRING: rmse
  LEARN_METRICS_TASK: min
  BOOSTING: gbdt #gbdt, dart, goss
  N_JOBS: 1
VALIDATION:
  VALIDATE_METRICS_STRING: mse
  CV:
    N_SPLITS: 3
    TRAIN_SIZE: 0.8
    TEST_SIZE: 0.2
SAVE_ERRORS: true
PREDICTION:
  SAVE_PREDICTIONS_TRAIN: true
  SAVE_PREDICTIONS_TEST: true